### ISSUE TITLE
There is no examples directory in the build folder

### ISSUE THREAD

**Issue by dwya222** [XianyiCheng/CMGMP#1]
After building, the build folder contains the following files
in `CMGMP/build`
```
ls
CMakeCache.txt  CMakeDoxyfile.in  CMakeDoxygenDefaults.cmake  CMakeFiles  cmake_install.cmake  cmgmp  Makefile  tests
```
There is no examples folder present at `./examples` as the documentation states

**Comment by XianyiCheng** [comment]
Fixed. The reason is that I commented the examples folder in CMakeLists.txt while debugging. If you pull the newest version, it should be good now.
